# Generated by Django 5.2.10 on 2026-03-28 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dcim", "0225_gfk_indexes"),
        ("extras", "0134_owner"),
        ("netbox_librenms_plugin", "0010_inventory_models"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="interfacetypemapping",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="modulebaymapping",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="devicetypemapping",
            name="netbox_device_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="librenms_device_type_mappings",
                to="dcim.devicetype",
            ),
        ),
        migrations.AlterField(
            model_name="inventoryignorerule",
            name="enabled",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="moduletypemapping",
            name="netbox_module_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="librenms_module_type_mappings",
                to="dcim.moduletype",
            ),
        ),
        migrations.AlterField(
            model_name="normalizationrule",
            name="scope",
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AddConstraint(
            model_name="interfacetypemapping",
            constraint=models.UniqueConstraint(
                fields=("librenms_type", "librenms_speed"), name="unique_interface_type_mapping"
            ),
        ),
        migrations.AddConstraint(
            model_name="modulebaymapping",
            constraint=models.UniqueConstraint(
                fields=("librenms_name", "librenms_class"), name="unique_module_bay_mapping"
            ),
        ),
    ]
