# Generated by Django 5.2.10 on 2026-02-17 12:29

import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("extras", "0134_owner"),
        ("netbox_librenms_plugin", "0010_add_moduletypemapping"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModuleBayMapping",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder),
                ),
                ("librenms_name", models.CharField(max_length=255)),
                ("librenms_class", models.CharField(blank=True, max_length=50)),
                ("netbox_bay_name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("tags", taggit.managers.TaggableManager(through="extras.TaggedItem", to="extras.Tag")),
            ],
            options={
                "ordering": ["librenms_name"],
                "unique_together": {("librenms_name", "librenms_class")},
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
