# Generated by Django 5.2.10 on 2026-03-28 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dcim", "0225_gfk_indexes"),
        ("netbox_librenms_plugin", "0011_rename_related_names"),
    ]

    operations = [
        migrations.AlterField(
            model_name="normalizationrule",
            name="manufacturer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="normalization_rules",
                to="dcim.manufacturer",
            ),
        ),
    ]
