# Generated by Django 5.2.10 on 2026-02-17 13:01

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dcim", "0225_gfk_indexes"),
        ("extras", "0134_owner"),
        ("netbox_librenms_plugin", "0011_modulebaymapping"),
    ]

    operations = [
        migrations.CreateModel(
            name="InterfaceNameRule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder),
                ),
                ("name_template", models.CharField(max_length=255)),
                ("channel_count", models.PositiveSmallIntegerField(default=0)),
                ("channel_start", models.PositiveSmallIntegerField(default=0)),
                ("description", models.TextField(blank=True)),
                (
                    "module_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interface_name_rules",
                        to="dcim.moduletype",
                    ),
                ),
                (
                    "parent_module_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="child_interface_name_rules",
                        to="dcim.moduletype",
                    ),
                ),
                ("tags", taggit.managers.TaggableManager(through="extras.TaggedItem", to="extras.Tag")),
            ],
            options={
                "ordering": ["module_type__model"],
                "unique_together": {("module_type", "parent_module_type")},
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
