# Generated by Django 5.2.10 on 2026-02-19 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dcim", "0225_gfk_indexes"),
        ("netbox_librenms_plugin", "0014_normalizationrule_manufacturer"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="interfacenamerule",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="interfacenamerule",
            name="device_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interface_name_rules",
                to="dcim.devicetype",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="interfacenamerule",
            unique_together={("module_type", "parent_module_type", "device_type")},
        ),
    ]
