# Generated by Django 5.2.10 on 2026-02-19 19:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_librenms_plugin", "0014_normalizationrule_manufacturer"),
    ]

    operations = [
        migrations.AddField(
            model_name="modulebaymapping",
            name="is_regex",
            field=models.BooleanField(default=False),
        ),
    ]
